ALTER TABLE anime MODIFY COLUMN `status` ENUM('WATCHED','WATCHING','SIMULCAST','SIMULCAST_AVAILABLE','DOWNLOADED','DOWNLOADING','NOT_DOWNLOADED','NO_SOURCE','UNAVAILABLE','CANCELLED','STORAGE_ONLY');
ALTER TABLE torrent MODIFY COLUMN `status` ENUM('STOPPED','VERIFY_QUEUED','VERIFYING','DOWNLOAD_QUEUED','DOWNLOADING','SEED_QUEUED','SEEDING');
ALTER TABLE broadcast MODIFY COLUMN `status` ENUM('UNKNOWN','SCHEDULED','ACTIVE','COMPLETED','CANCELED');
ALTER TABLE interest MODIFY COLUMN `level` ENUM('INTERESTED','NEUTRAL','NOT_INTERESTED');
ALTER TABLE watchlist MODIFY COLUMN `status` ENUM('WATCHED','WATCHING','SIMULCAST','SIMULCAST_AVAILABLE','DOWNLOADED','DOWNLOADING','NOT_DOWNLOADED','NO_SOURCE','UNAVAILABLE','CANCELLED','STORAGE_ONLY');