CREATE TABLE `torrent`
(
    `id`                        INT          NOT NULL,
    `eta`                       BIGINT       NOT NULL,
    `added_date`                BIGINT       NOT NULL,
    `download_dir`              VARCHAR(255) NULL,
    `name`                      VARCHAR(255) NOT NULL,
    `is_finished`               BIT(1)       NOT NULL,
    `is_stalled`                BIT(1)       NOT NULL,
    `peers_connected`           BIGINT       NOT NULL,
    `peers_getting_from_us`     BIGINT       NOT NULL,
    `peers_sending_to_us`       BIGINT       NOT NULL,
    `queue_position`            BIGINT       NOT NULL,
    `rate_download`             BIGINT       NOT NULL,
    `rate_upload`               BIGINT       NOT NULL,
    `left_until_done`           BIGINT       NOT NULL,
    `metadata_percent_complete` BIGINT       NOT NULL,
    `percent_done`              DECIMAL      NULL,
    `upload_ratio`              DECIMAL      NULL,
    `uploaded_ever`             DECIMAL      NULL,
    `seed_ratio_limit`          DECIMAL      NULL,
    `seed_ratio_mode`           DECIMAL      NULL,
    `size_when_done`            BIGINT       NOT NULL,
    CONSTRAINT `pk_torrent` PRIMARY KEY (`id`)
);
